CREATE DATABASE ProjectAkhirITDiv
USE ProjectAkhirITDiv

BEGIN TRAN
CREATE TABLE msCustomer (
	CustomerID VARCHAR(6) PRIMARY KEY CHECK (CustomerID LIKE 'CID[0-9][0-9][0-9]') NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Gender CHAR(6) CHECK(Gender IN('MALE','FEMALE'))NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	Phone VARCHAR(50) UNIQUE NOT NULL,
	DateOfBirth DATE NOT NULL,
	Stsrc CHAR(1) NOT NULL,
	UserIn VARCHAR(50) NOT NULL,
	UserUp VARCHAR(50) NOT NULL,
	DateIn DATETIME NOT NULL,
	DateUp DATETIME NOT NULL
)

CREATE TABLE msHotel (
	HotelID VARCHAR (6) PRIMARY KEY CHECK (HotelID LIKE 'HTL[0-9][0-9][0-9]') NOT NULL,
	HotelName VARCHAR (50) NOT NULL,
	HotelDescription VARCHAR (50) NOT NULL,
	PhoneNumber VARCHAR (50) UNIQUE NOT NULL,
	Email VARCHAR (50) UNIQUE NOT NULL,
	[Address] VARCHAR (50) NOT NULL,
	[Rating] FLOAT NOT NULL,
	[Image] VARCHAR (50) NOT NULL,
	Stsrc CHAR(1) NOT NULL,
	UserIn VARCHAR(50) NOT NULL,
	UserUp VARCHAR(50) NOT NULL,
	DateIn DATETIME NOT NULL,
	DateUp DATETIME NOT NULL
)

CREATE TABLE msRoom (
	RoomID VARCHAR(6) PRIMARY KEY CHECK (RoomID LIKE 'RM[0-9][0-9][0-9][0-9]') NOT NULL,
	HotelID VARCHAR(6) FOREIGN KEY REFERENCES msHotel ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	RoomDescription VARCHAR(50) NOT NULL,
	Price INT NOT NULL,
	RoomAvailable VARCHAR(15) NOT NULL,
	RoomType VARCHAR(15) NOT NULL,
	RoomBook VARCHAR (15) NOT NULL,
	[Image] VARCHAR(50) NOT NULL,
	Stsrc CHAR(1) NOT NULL,
	UserIn VARCHAR(50) NOT NULL,
	UserUp VARCHAR(50) NOT NULL,
	DateIn DATETIME NOT NULL,
	DateUp DATETIME NOT NULL
)

CREATE TABLE trCustomerBooking (
	BookingID VARCHAR(6) PRIMARY KEY CHECK (BookingID LIKE 'BOOK[0-9][0-9]') NOT NULL,
	CustomerID VARCHAR(6) REFERENCES msCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	RoomID VARCHAR(6) REFERENCES msRoom(RoomID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	BookingDate DATE NOT NULL,
	TotalPrice INT NOT NULL,
	BookingStatus VARCHAR(50) NOT NULL,
	CheckInDate DATETIME NOT NULL,
	CheckOutDate DATETIME NOT NULL,
	TotalNights VARCHAR (10) NOT NULL,
	Stsrc CHAR(1) NOT NULL,
	UserIn VARCHAR(50) NOT NULL,
	UserUp VARCHAR(50) NOT NULL,
	DateIn DATETIME NOT NULL,
	DateUp DATETIME NOT NULL
)

CREATE TABLE trCustomerPayment (
	PaymentID VARCHAR (6) PRIMARY KEY CHECK (PaymentID LIKE 'PID[0-9][0-9][0-9]') NOT NULL,
	BookingID VARCHAR (6) REFERENCES trCustomerBooking(BookingID) ON UPDATE CASCADE ON DELETE CASCADE,
	CustomerID VARCHAR (6) REFERENCES msCustomer(CustomerID),
	PaymentMethod VARCHAR(50) NOT NULL,
	PaymentAmount INT NOT NULL,
	PaymentDate DATE NOT NULL,
	Stsrc CHAR(1) NOT NULL,
	UserIn VARCHAR(50) NOT NULL,
	UserUp VARCHAR(50) NOT NULL,
	DateIn DATETIME NOT NULL,
	DateUp DATETIME NOT NULL
)

--INSERT DATA

INSERT INTO msCustomer VALUES
('CID001', 'Jessica', 'Jane', 'FEMALE', 'jessicajane@gmail.com', 'jj123', '08788901929', '1999-02-19', 'A', ORIGINAL_LOGIN(), ORIGINAL_LOGIN(), GETDATE(), GETDATE());

INSERT INTO msHotel VALUES
('HTL001', 'Royal Safari Garden', 'Description', '02518253000', 'reservation@royalsafari.com', 'Cisarua', '90', 'LinkImage', 'A', ORIGINAL_LOGIN(), ORIGINAL_LOGIN(), GETDATE(), GETDATE())

INSERT INTO msRoom VALUES
('RM1001', 'HTL001', '', '1000000', '10', 'Deluxe', '5', 'LinkImage', 'A', ORIGINAL_LOGIN(), ORIGINAL_LOGIN(), GETDATE(), GETDATE());

INSERT INTO trCustomerBooking VALUES
('BOOK01', 'CID001', 'RM1001', '2021-04-20', '2000000', 'BOOKED', '2021-04-22 13:17:17', '2021-04-24 13:00:05', '2', 'A', ORIGINAL_LOGIN(), ORIGINAL_LOGIN(), GETDATE(), GETDATE())

INSERT INTO trCustomerPayment VALUES
('PID111', 'BOOK01', 'CID001', 'BCA Transfer', '2000000', '2021-04-20', 'A', ORIGINAL_LOGIN(), ORIGINAL_LOGIN(), GETDATE(), GETDATE());

ROLLBACK
--DROP TABLE Customer
--DROP TABLE Room
--DROP TABLE Booking
--DROP DATABASE ProjectAkhirITDiv
SELECT * FROM msCustomer
SELECT * FROM trCustomerBooking
SELECT * FROM msRoom
SELECT * FROM msHotel
SELECT * FROM trCustomerPayment